services:
  video-backend:
    image: ${IMAGE}
    container_name: ${APP_NAME}
    ports:
      - "8888:8888"
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    networks:
      - video

networks:
  video:
    external: true
